name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: [
          win-x64,
          linux-x64,
          linux-arm64,
          osx-arm64
        ]

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          cache: true

      - name: Restore
        run: dotnet restore src/TreeSync.Cli/TreeSync.Cli.csproj

      - name: Restore
        run: dotnet restore src/TreeSync.Cli/TreeSync.Cli.csproj

      - name: Publish
        run: |
          dotnet publish src/TreeSync.Cli/TreeSync.Cli.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -o publish/${{ matrix.rid }}

      - name: Package
        run: |
          cd publish/${{ matrix.rid }}
          zip -r ../../TreeSync-${{ matrix.rid }}.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TreeSync-${{ matrix.rid }}
          path: TreeSync-*.zip


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install semantic-release
        run: |
          npm init -y
          npm install semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release